
defaults:
  - ema
  - model_checkpoint
  # - early_stopping
  # - learning_rate_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "ldm-epoch@{epoch}-step@{step}-val_zinc_valid_rate@{val_zinc/valid_rate:.4f}"
  monitor: "val_zinc/valid_rate"
  mode: "max"
  save_last: True

# early_stopping:
#   monitor: "val/valid_rate"
#   patience: 100
#   mode: "max"
